### ISSUE TITLE
Cannot convert ResNet50 to onnx model (ValueError: setting an array element with a sequence in in create_zero_padding)

### ISSUE THREAD

**Issue by Daiver** [leodestiny/onnx-keras#5]
Hello! First of all thank you for your project!

But i have a problem with converting default ResNet50 model to onnx
Here a minimal example
```
import sys
PATH_TO_ONNX_KERAS = '<path to repo>'
sys.path.append(PATH_TO_ONNX_KERAS)
import frontend as onnxkeras
import keras
import onnx

if __name__ == '__main__':
    kerasModel = keras.applications.ResNet50()
    onnxModel = onnxkeras.keras_model_to_onnx_model(kerasModel)
    onnxkeras.save(onnxModel, 'keras_resnet.proto')
```
It gives me following output
```
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-05-30 11:09:32.717600: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-05-30 11:09:32.822003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-30 11:09:32.822255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8225
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.00GiB
2018-05-30 11:09:32.822268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-05-30 11:09:32.976717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-30 11:09:32.976745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-05-30 11:09:32.976750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-05-30 11:09:32.976910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6763 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
[1, 3, 224, 224]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    onnxModel = onnxkeras.keras_model_to_onnx_model(kerasModel)
  File "/home/daiver/coding/onnx-keras/frontend.py", line 100, in keras_model_to_onnx_model
    model = make_model(cls.keras_graph_to_onnx_graph(model, name=model_name),
  File "/home/daiver/coding/onnx-keras/frontend.py", line 145, in keras_graph_to_onnx_graph
    graph_input_list, weight_list, node_list = handler(layer)
  File "/home/daiver/coding/onnx-keras/frontend.py", line 998, in create_zero_padding2D
    return cls.create_zero_padding(layer, 2)
  File "/home/daiver/coding/onnx-keras/frontend.py", line 837, in create_zero_padding
    pads = np.asarray(padding).transpose().flatten().tolist()
  File "/home/daiver/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

PS Sorry for my poor English

**Comment by leodestiny** [comment]
Thanks for reporting the bug.
I used wrong syntax of tuple, so I changed code into np.array and fixed it.
You can try latest commit. 
And sorry for delayed reply.

**Comment by Daiver** [comment]
Hi @leodestiny ! I am happy for your answer, sorry for delay too.

Unfortunately i still have some problems with ResNet50 (same minimal example)
```
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-06-12 11:18:09.369258: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-12 11:18:09.461950: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-12 11:18:09.462173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8225
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.32GiB
2018-06-12 11:18:09.462186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-06-12 11:18:09.618871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-12 11:18:09.618899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-06-12 11:18:09.618905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-06-12 11:18:09.619028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7076 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
[1, 3, 224, 224]
Traceback (most recent call last):
  File "main2.py", line 13, in <module>
    onnxModel = onnxkeras.keras_model_to_onnx_model(kerasModel)
  File "/home/daiver/coding/onnx-keras/frontend.py", line 104, in keras_model_to_onnx_model
    check_model(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: consumed_inputs

==> Context: Bad node spec: input: "conv1/BiasAdd:0" input: "bn_conv1/gamma:0" input: "bn_conv1/beta:0" input: "bn_conv1/moving_mean:0" input: "bn_conv1/moving_variance:0" output: "bn_conv1/cond/Merge:0" name: "bn_conv1" op_type: "BatchNormalization" attribute { name: "consumed_inputs" ints: 0 ints: 0 ints: 0 ints: 1 ints: 1 type: INTS } attribute { name: "epsilon" f: 0.001 type: FLOAT } attribute { name: "momentum" f: 0.99 type: FLOAT } attribute { name: "spatial" i: 1 type: INT }

```
btw my tf version is `1.7.0` and keras version is `2.1.5`

Should i create new issue for this?

**Comment by arindam93** [comment]
Having the same Validation Error. Can anyone help?
